import { Component, OnInit } from '@angular/core';
import {Post} from '../Post';
import {User} from '../User';

@Component({
  selector: 'app-home',
  templateUrl: './home.component.html',
  styleUrls: ['./home.component.css']
})
export class HomeComponent implements OnInit {

  // Test cases for the component, these objects should be generated by services

  amy = new User('Amy', '/assets/images/resources/admin.jpg');
  alexis = new User('Alexis', '/assets/images/resources/nearly1.jpg');
  sarah = new User('Sarah', '/assets/images/resources/nearly6.jpg');
  users = new Map<string, string>([
    [this.amy.userName, this.amy.userIconURL],
    [this.alexis.userName, this.alexis.userIconURL],
    [this.sarah.userName, this.sarah.userIconURL]
  ]);
  comments1 = [
    ['Sarah', 'Oh my god, you look amazing dear! Look at them beautiful blue eyes shining like diamonds!',
      '2021-05-01 17:35'],
    ['Alexis', 'Oh you are so cute !', '2021-05-01 18:32']
  ];
  comments2 = [
    ['Sarah', 'Why didn\'t you take me with you in this trip?', '2021-04-30 19:34'],
    ['Amy', 'This is heaven on earth!', '2021-04-30 19:44']
  ];
  post1 = new Post(this.amy, 'Having fun in San Francisco!', '/assets/images/resources/user-post.jpg',
    '2021-05-01  16:40', 2500, this.comments1);
  post2 = new Post(this.alexis, 'Having fun in New York!', '/assets/images/resources/user-post6.jpg',
    '2021-04-30  18:32', 2200, this.comments2);
  posts = [this.post1, this.post2];
  curUser = new User('Amy', '/assets/images/resources/admin.jpg' );

  // End of test cases


  text = '';
  likedPosts = new Set<Post>();

  postImg(){
    if(this.text) {
      const comm = Array();
      const date = new Date().toISOString().slice(0, 16).replace('T',' ');
      let newPost = new Post(this.curUser, this.text, '', date, 0, comm);
      this.posts.push(newPost);
      this.text = '';
    }
  }
  putComment (commentPost: Post){
    const date = new Date().toISOString().slice(0, 16).replace('T', ' ');
    commentPost.comments.push( [this.curUser.userName, commentPost.commentArea, date]);
    commentPost.commentArea = '';
  }
  pressHeart(post: Post){
    if (this.likedPosts.has(post)) {
      this.likedPosts.delete(post);
      post.liked = false;
      post.likesCount--;
    } else {
      this.likedPosts.add(post);
      post.liked = true;
      post.likesCount++;
    }
  }
  constructor() { }

   ngOnInit(): void {
  }

}
